[package]
name = "epitaph"
description = "Types and macros for more detailed errors."
version = "0.2.0"
authors = ["Jameson Ernst <j.patrick.ernst@gmail.com>"]
repository = "https://github.com/jpernst/epitaph"
license = "MIT"


[dependencies.alternate-future]
optional = true

